# print(y)
plt.plot(x,naprej,'-',x,izo,'o')
plt.grid()
plt.title('debelina: 1   stevilo nevtronov: 100000')
plt.ylabel('R-odbojnost')
plt.xlabel(r'$\lambda$-povprečna prosta pot')
plt.legend(['naprej/nazaj','izotropno'])
plt.savefig('9_3_lamda.png')
# plt.xscale('log')
plt.show()